Fix %-interpolation error
9c352d7 (Always pass an exception as first argument of ui.error,
2026-04-01) rearranged some of the arguments to `ui.error` in
`folder/IMAP.py`, but while it removed one of the %-interpolation
entries in the string to be interpolated, it didn't remove the argument
in the interpolation tuple.  This leads to errors like the below:

      File "offlineimap/folder/IMAP.py", line 863, in _fetch_from_imap
        "While fetching msg %r in folder %r."
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        " Query: %s Retrying (%d/%d)" % (
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
            e, uids, self.name, query,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~
            retry_num - fails_left, retry_num))
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    TypeError: %d format: a real number is required, not str

Remove the argument from the interpolation tuple that has now been
removed from the string, so the tuple parameters and string contents
match again.

Signed-off-by: Adam Dinwoodie <adam@dinwoodie.org>